# Generated by Django 3.2.16 on 2026-05-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0006_alter_candies_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candies',
            name='ingredients',
            field=models.TextField(default='Не указан'),
        ),
        migrations.AddField(
            model_name='candies',
            name='weight',
            field=models.SmallIntegerField(default=0),
        ),
    ]
