# Generated by Django 3.2.16 on 2026-05-29 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20260529_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
