# Generated by Django 3.2.16 on 2026-03-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candies',
            options={'verbose_name': 'Сладость', 'verbose_name_plural': 'Сладости'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
