# Generated by Django 3.2.16 on 2026-03-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0002_auto_20260317_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candies',
            old_name='descreption',
            new_name='description',
        ),
    ]
