# Generated by Django 3.2.16 on 2026-05-25 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0003_rename_descreption_candies_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='candies',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='candies',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candy.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='candies',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='candies',
            name='is_on_main',
            field=models.BooleanField(default=True, verbose_name='На главной'),
        ),
        migrations.AlterField(
            model_name='candies',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='candies',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='output_order',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
    ]
