# Generated by Django 3.2.16 on 2026-05-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0004_auto_20260525_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='candies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='choices/', verbose_name='Изображение'),
        ),
    ]
