# Generated by Django 3.2.16 on 2026-05-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy', '0005_candies_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='candies/', verbose_name='Изображение'),
        ),
    ]
